name: 'github-actions-docker-swarm-env'
author: "Erik Petrosyan <dev.erikpetrosyan@gmail.com>"
description: "Deploy a Docker Swarm stack over SSH with environment variable injection."
inputs:
  ssh_private_key:
    description: "SSH private key"
    required: true
  ssh_host:
    description: "Hostname or IP of the Swarm manager"
    required: true
  ssh_user:
    description: "SSH username"
    required: true
  ssh_remote_port:
    description: "SSH port"
    default: "22"
    required: false
  file:
    description: "Path to stack/compose file (on remote, relative to remote_workdir)"
    required: true
  stack_name:
    description: "Name of stack"
    required: true
  env_list:
    description: "Multi-line KEY=VALUE list of env vars to export before running docker stack"
    required: false
  ssh_remote_known_hosts:
    description: "Optional known_hosts line for your SSH server (host key). If omitted, ssh-keyscan is used."
    required: false
  remote_workdir:
    description: "Optional remote working directory. Defaults to /home/<ssh_user>/${GITHUB_REPOSITORY}"
    required: false


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "upload-cloud"
  color: "blue"
